### ISSUE TITLE
NoClassDefFoundError  error occurs

### ISSUE THREAD

**Issue by jfenuk** [vbauer/yandex-translate-api#1]
Steps to reproduce: 
- Create empty Maven project with the following pom.xml:

> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0"
>          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
> 
> ```
> <groupId>com.acme</groupId>
> <artifactId>yandex-translate</artifactId>
> <version>1.0-SNAPSHOT</version>
> 
> <dependencies>
>     <dependency>
>         <groupId>com.github.vbauer</groupId>
>         <artifactId>yandex-translate-api</artifactId>
>         <version>1.2.2</version>
>     </dependency>
> </dependencies>
> 
> <repositories>
>     <repository>
>         <id>jitpack.io</id>
>         <url>https://jitpack.io</url>
>     </repository>
> </repositories>
> ```
> 
> </project>
- Execute the following peace of code:
  
  ```
   api.detectionApi().detect("Hello, World!");
  ```
- The following error occurs:

> Exception in thread "main" java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
>     at com.github.vbauer.yta.service.transport.impl.DataConverterImpl.createConverter(DataConverterImpl.java:59)
>     at com.github.vbauer.yta.service.transport.impl.DataConverterImpl.<clinit>(DataConverterImpl.java:44)
>     at com.github.vbauer.yta.service.basic.ApiContext.of(ApiContext.java:80)
>     at com.github.vbauer.yta.service.YTranslateApiImpl.<init>(YTranslateApiImpl.java:58)

**Comment by vbauer** [comment]
@jfenuk Thank you for the found bug. I've just written to author of `ru.vyarus.java-lib` & `ru.vyarus.pom` Gradle plugins. I hope he will fix this problem in the nearest future.

JFYI: You can use workaround: add dependency on `com.google.code.gson:gson:2.6.2` in you project.

**Comment by vbauer** [comment]
Fixed in the version 1.2.3.
